[project]
name = "disbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.31.0",
    "discord>=2.3.2",
    "discord-py>=2.6.4",
    "dotenv>=0.9.9",
    "loguru>=0.7.3",
]
